#!/usr/bin/perl -w

use strict;
use PerlBench qw(timeit sec_f);
use Getopt::Long qw(GetOptions);

my %opt;
GetOptions(\%opt,
   'repeat=n',
   'use-avg',
   'verbose',
   'print-loop-overhead',
) || usage();

my $code = shift || @ARGV;
usage() if @ARGV;

$code .= ";" unless $code =~ /;\s*$/;

my $res = timeit($code, repeat => $opt{repeat}, verbose => $opt{verbose});
die "Failed" unless $res;

my $t = $res->{$opt{use_avg} ? "avg" : "med"};
my $d = $res->{stddev}*2;
print sec_f($t, $d), "\n";

if (my $o = $res->{loop_overhead_relative}) {
    $o *= 100;
    printf "(%.*f%% loop overhead)\n", ($o > 10 ? 0 : 1), $o
	if $o > 10 || $opt{'print-loop-overhead'};
}

if (0) {
    require Data::Dump;
    delete $res->{x};
    delete $res->{t};
    Data::Dump::dump($res);
}

sub usage {
    (my $progname = $0) =~ s,.*/,,;
    die "Usage: $progname [options] <perlcode>\n";
}
